### ISSUE TITLE
message from supercomputer when running our model on it

### ISSUE THREAD

**Issue by bianrq** [trophia/sna1#12]
terminate called after throwing an instance of 'boost::filesystem::filesystem_error
  what():
Aborted (core dumped)

**Comment by nokome** [comment]
This looks like it occurred because the `output` folder is missing. Create it first (`mkdir -p output/fishes`) and then try running again. I will write some code to ensure all necessary folders are created on initialisation to avoid this in future.

Note that you will need to copy the `input` folder to the supercomputer too when we have files in there.
