### ISSUE TITLE
Output the stock biomass scalar value  

### ISSUE THREAD

**Issue by mckenziej** [trophia/sna1#20]
Please output the stock biomass agent scalar value

**Comment by nokome** [comment]
Thanks for this.

The new file `output/fishes/values.tsv` contains summary values related to the fish population simulated:

- size: the size of the vector of simulated fish (this may be above `fishes_seed_number` for example due to recruitment variation causing the population size to grow above the seed size)
- alive : the simulated number of *alive* fish in the population in the *last year* e.g. `492813`
- scalar : the scalar used to scale the simulated population to the real population e.g. `244.498`
- number : the scaled number of fish in the populaion in the *last year* e.g. `1.20492e+08`
