### ISSUE TITLE
Please provide example of exponential growth parameterisation in Readme file

### ISSUE THREAD

**Issue by mckenziej** [trophia/sna1#22]

**Comment by nokome** [comment]
See https://github.com/trophia/sna1#growth . BUT there seems to be a problem when using exponential growth - I'm working on that now.

**Comment by nokome** [comment]
The issue I was seeing occurred when there is a high `fishes_linf_sd`. For some reason, with the exponential model that is causing a `nan` in biomass (a few fish with undefined growth ?). I found that reducing `fishes_linf_sd` to 1 avoids this issue i.e:

```json
    "fishes_growth_model": "e",
    "fishes_k_mean": 0.1,
    "fishes_k_sd": 0.02,
    "fishes_linf_mean": 60,
    "fishes_linf_sd": 1,
```

I have added some fish growth trajectories to the standard outputs and a script in `reports/fishes/growth.R` which produces some diagnostic plots e.g for the above pars

![image](https://user-images.githubusercontent.com/1152336/26854257-787ccc8c-4b69-11e7-9c8e-76d718348820.png)

You'll notice that the mosel runs slower with exponential model because of the extra calcs involved. We can optimise this.
