### ISSUE TITLE
Delete fish from memory when fish dies

### ISSUE THREAD

**Issue by Craig44** [trophia/sna1#27]
Can I ask why an agent object would remain in memory even after it dies?

Have you thought about deconstructing an agent when it dies, and then the fishes object is only alive fish, this would save a lot of checks seeing whether every agent is alive?

Is there a process or model quantity that is necessary to know when or how many dead fish are about?

**Comment by nokome** [comment]
Hi @Craig44 

> Can I ask why an agent object would remain in memory even after it dies?

That is, of course, a really good question to ask. And something that should probably be justified in the documentation. The reason for the current implementation approach is my  _assumption_ that using a `std::vector` of fish would be faster than using a `std::list`. 

As you probably know, in C++ vectors and lists have differing performance for various tasks (e.g. https://baptiste-wicht.com/posts/2012/11/cpp-benchmark-vector-vs-list.html). In particular,  [random access is much faster for vectors and insertion/deletion is much faster for lists](http://thispointer.com/difference-between-vector-and-list-in-c/). Because in a stochastic model like this random access is important (to probabilistically select fish) using `std:vector` seems the best alternative.

> Have you thought about deconstructing an agent when it dies, and then the fishes object is only alive fish, this would save a lot of checks seeing whether every agent is alive?

The good thing about `std::vectors` is that they occupy contiguous memory so are more memory cache friendly. But they suck for insertion/deletion: the whole vector gets reallocated for each insertion/deletion (I think this is right). So, rather than do a bunch of expensive memory reallocation the approach I took was to use a dead/alive boolean flag and treat a dead fish as a 'slot' in the population where are new recruit can be copied to.

The assumption here is that the checking of dead/alive is less expensive than reallocating the array. I haven't tested that. It would make an interesting mini-study to test the performance of these alternatives using realistically sized populations

> Is there a process or model quantity that is necessary to know when or how many dead fish are about?

No, it's just an artefact of the implementation approach described above.

**Comment by Craig44** [comment]
That makes complete sense, I was too busy getting caught up in the fish class that I forgot how they were stored and accessed in the fishes class, thanks for the reply
